Pujo-Atlas-Kolkata/PujoAtlasKol-Web

.vscode/extensions.json
CONTRIBUTING.md

docs: added vscode extensions

---

.husky/commit-msg
.husky/pre-commit
.husky/pre-push

cli: removed branch name checks

---

src/components/shared/Footer.astro
src/components/shared/Navbar.tsx
src/constants/index.ts
src/constants/socials.ts

Closes #41 
---
Refactored and moved all social media links to separate constants folder

chore: added socials link to constants

---

.github/ISSUE_TEMPLATE/dev_chore.yml

Closes #43 
---
Added an option to issue type to add a developer chore issue
---

chore: added chore issue

---

netlify.toml
src/layouts/Layout.astro
src/pages/index.astro

Closes #30, #6
---
- add font catching & preload
- remove layout shift on page visit
- add favicon caching
---
N/A

feat: netlify cache test

---

astro.config.mjs
package-lock.json
package.json
src/layouts/Layout.astro

Closes #48
---
added Google Analytics & Partytown
---
N/A

feat: add google analytics & partytown

---

src/components/Carousel/index.tsx

Closes #<issue>
---
set carousel autplay delay to 3000ms, stop autoplay on mouse enter & restart on mouse exit
---
N/A

feat: set carousel autplay delay to 3000ms, stop autoplay on mouse enter & restart on mouse exit

---

src/pages/bn/index.astro
src/pages/index.astro

---
made the coming soon capsule fully rounded
---

feat: make the coming soon capsule fully rounded

---

src/layouts/Layout.astro
src/pages/index.astro

---
fixed smooth scroll & removed scroll down indicator on mobile screens
---
N/A

fix: smooth scroll & remove scroll down indicator on mobile screens

---

src/layouts/Layout.astro
src/pages/bn/index.astro
src/pages/index.astro
tailwind.config.js

Closes #79
---
1) reconfigure Noto Sans Bengali
2) invert scroll bar thumb & trackbar colors

fix: reconfigure Noto Sans Bengali + invert scroll bar thumb & trackbar colors

---

astro.config.mjs
package-lock.json
package.json
src/components/Carousel/index.tsx
src/components/shared/Footer.astro
src/components/shared/Header.astro
src/layouts/Layout.astro
src/pages/bn/index.astro
src/pages/index.astro

Closes #75 
---
Fixed bugs
---
N/A

fix: minor UI fixes 

---

src/components/app/shared/BottomNav.astro
src/pages/app/booths.astro
src/pages/app/help.astro

feat: add functionality to Help page

---

src/components/shared/Footer.astro
src/components/shared/Navbar.tsx

feat: prep for Netlify OSS Sponsorship

---

package-lock.json
src/components/app/shared/NearMeCard.astro
src/pages/app/index.astro

Closes #89 
---
1. Added UI for "Near Me" card component
---

feat: create UI for home page in webapp

---

src/pages/bn/index.astro

feat: add "Features" & "Get Started" buttons to /bn/ page

---

.github/pull.yml
src/components/app/map/ClusterMarker.tsx
src/components/app/map/GoogleMap.tsx
src/components/app/map/LocationMarker.tsx
src/components/app/map/types.ts
src/constants/location.ts
src/pages/app/pandals.astro

feat: fetch pandal list from BE + fix: & toggle location name & navigation button bug

---

src/components/app/home/Cards/Cards.tsx
src/components/app/home/Cards/PandalCard.tsx
src/constants/location.ts
src/layouts/WebAppLayout.astro

feat: plug-in api for Trending Pandals

---

package-lock.json
package.json
src/components/app/home/Cards/Cards.tsx
src/components/app/shared/AppHeader.astro
src/pages/bn/index.astro
src/pages/index.astro

feat: "near me" toast + web app header chip + /bn/ landing font fix

---

package-lock.json
src/components/Carousel/Cards.tsx
src/components/Carousel/CarouselCard.tsx
src/components/Carousel/index.tsx

Closes #114 
---
replaced images in carousel present in landing page with trending pandal cards
---

feat: replace images in carousel present in landing page with Trending Pandal Cards #114

---

src/pages/bn/index.astro
src/pages/index.astro

fix: overflow-x

---

src/components/app/home/Cards/Cards.tsx
src/components/app/home/Cards/PandalCard.tsx
src/components/app/map/GoogleMap.tsx

Closes #122 
---
clicking on pandal cards now shows the direction from userlocation to pandal in a new tab
---

feat: nearme and trending cards are not clickable

---

src/components/app/home/Cards/PandalCard.tsx

feat: Home tab UI Tweaks

---

src/components/app/home/Cards/Cards.tsx
src/components/app/home/Cards/PandalCard.tsx

feat: update ranking when user clicks on "Get Directions" & "Show On Map" + change button BG Color

---

src/components/app/shared/Search/input.tsx

feat: when user clicks on any pandal search result - take them to /app/pandals and pan the map on that location marker

---

src/components/app/home/Cards/PandalCard.tsx
src/components/app/map/GoogleMap.tsx
src/components/app/map/UserLocation.tsx
src/components/app/shared/Search/input.tsx

feat: make pandal location name and "navigate" button show up automatically when searched from searchbar or from Home tab pandal cards

---

src/components/app/shared/AppHeader.astro
src/components/app/shared/SettingsFlyout.tsx
tailwind.config.js

Closes #132
---
settings icon now rotates slightly if we click on it
---

feat: add onClick feedback to settings icon

---

src/components/Members/index.tsx
src/components/shared/Header.astro
src/components/shared/Navbar.tsx
src/constants/team.ts
src/pages/bn/team.astro
src/pages/team.astro

Closes #130 
---
Added a teams page to showcase all our technical and non-technical contributors
---

feat: teams page

---

package-lock.json
src/components/app/home/Cards/Cards.tsx
src/components/app/home/Cards/PandalCard.tsx

fix: changed the error UI in the home page when location is disabled with details as requested by naget

---

src/components/app/shared/Search/input.tsx
src/components/app/shared/SettingsFlyout.tsx

fix: minor UI enhancements as requested by naget

---

src/components/app/home/Cards/PandalCard.tsx

fix: changed buttons on the cards to back as it was

---

src/components/app/home/Cards/Cards.tsx
src/components/app/shared/AppHeader.astro
src/pages/app/help.astro
src/pages/app/pandals.astro

fix: v.1.0.1 minor ui tweaks

---

.astro/settings.json
package-lock.json
package.json
src/components/Carousel/Cards.tsx
src/components/app/home/Cards/Cards.tsx
src/components/app/shared/SettingsFlyout.tsx

feat: to create two buttons in the drawer container, showing status if the user has accepted or rejected location permission with toast

---

src/components/app/home/Cards/Cards.tsx
src/components/app/home/Cards/PandalCard.tsx
src/types/pujo.ts

feat: in "Home" tab, for each pandal card - show its nearest metro station

---

package-lock.json
src/components/app/home/Cards/Cards.tsx

Closes #176 
---
"Near me" and "Trending" buttons are now scrollable
---

fix!: Make only the search bar sticky, allowing "Near Me" and "Trending" buttons to scroll

---

src/components/shared/Navbar.tsx

Closes #186
---
Added hard width to sponsor logos
---

fix: image scaling firefox fix

---

.github/workflows/snyk-weekly.yml

Closes 
---
- Runs Snyk test every monday on 2am
- Generate the report as html
- Publish the report as Github Pages
---

ci: added github cron
